name: the_internet
description: A library to easily create and configure a MockHttpClient
version: 1.0.0
homepage: https://github.com/avbk/the_internet

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  dio: ^3.0.9

dev_dependencies:
  lint: ^1.1.1
  test: ^1.6.0
