name: the_internet
description: A library to easily create and configure a MockHttpClient
version: 1.0.0
homepage: https://github.com/avbk/the_internet

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http: ^0.13.0
  dio: ^4.0.0-beta5
  uri: ^1.0.0

dev_dependencies:
  lint: ^1.5.2
  test: ^1.16.5
    #test_coverage: ^0.4.1

