name: the_internet
description: A library to easily create and configure a MockHttpClient
version: 1.0.0
homepage: https://github.com/avbk/the_internet

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  dio: ^4.0.0
  uri: ^1.0.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.4
    #test_coverage: ^0.4.1

